<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class facturas extends Model
{
	use SoftDeletes; 
	protected $primaryKey = 'idFactura';
	protected $fillable=['idFactura',
	'numeroFactura',
	'fechaVencimiento',
	'idb',
	'idCotizacion',
	'montoFactura',
	'periodoPago',
	'fechaFactura',
	'fechaPago',
	'tipoMoneda',
	'idc',
	'cambioFactura',
	'montoPesos',
	'saldo',
	'cambioReal',
	'montoUsd',
	'observacionesFactura',
	'ordenCompra',
	'factura',
	'comprobantePago',
	'archivo',
	'archivoFactura',
	'archivoPago',
	'xmlFactura',
	'metodoPago',
	'estatusEntrega',
	'estatusPortal',
	'estatusPago',
	'cashFlow',
	'numeroRemision',
	'archivoRemision',
	'numeroEntrada',
	'complementoPago',
	'idServicios',
	'idSucursal',
	'nombreEmpresa',
	'tipoServicio',
	'numeroDocumento',
	'archivoOtro',
	'adenda',
	'archivoAdenda',
	'numeroAnexo1',
	'anexo1',
	'numeroAnexo2',
	'anexo2',
	'numeroAnexo3',
	'anexo3',
	'numeroAnexo4',
	'anexo4',
	'numeroAnexo5',
	'anexo5',
	'numeroAnexo6',
	'anexo6',
	'numeroAnexo7',
	'anexo7',
	'numeroAnexo8',
	'anexo8',
	'numeroAnexo9',
	'anexo9',
	'numeroAnexo10',
	'anexo10',
	'servicioActivo'];
	protected $date=['deleted_at'];
}
